name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Installing dependencies
      - name: Installing dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: node tests/test.js

      # Step 5: Building Docker image
      - name: Building Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-cicd-app:latest .

      # Step 6: DockerHub Login
      - name: DockerHub Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 7: Push image to DockerHub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-cicd-app:latest
